### ISSUE TITLE
is this project abandoned?

### ISSUE THREAD

**Issue by rvision** [borm/use-form#17]
Hi @borm - is this project abandoned? 

If it is, I would like to use this name, "use-form" since I am working on a similar form framework.

Please, let me know, thanks

**Comment by borm** [comment]
hi @rvision, not abandoned, but, if u already have pretty better solution/realization, let me look at it

**Comment by rvision** [comment]
@borm sure, let me first just finish example on codesandbox and cleanup code.
I'm busy with some other things ATM, but will ping you when done

**Comment by rvision** [comment]
sent you an email yesterday
